name: CameraApp
options:
  bundleIdPrefix: com.micamara
  deploymentTarget:
    iOS: "15.0"

targets:
  CameraApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: CameraApp
        excludes:
          - "Info.plist"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.micamara.app
        INFOPLIST_FILE: CameraApp/Info.plist
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_IDENTITY: ""
        AD_HOC_CODE_SIGNING_ALLOWED: "YES"
